"""Add plant model

Revision ID: 07490ad2fd6e
Revises: 3eee7af9a951
Create Date: 2022-04-25 18:58:32.127544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07490ad2fd6e'
down_revision = '3eee7af9a951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=50), nullable=False),
    sa.Column('scientific_name', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_name'),
    sa.UniqueConstraint('scientific_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    # ### end Alembic commands ###
