"""Plantbook

Revision ID: a6c0614a4efd
Revises: 07490ad2fd6e
Create Date: 2022-04-26 10:45:15.934013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c0614a4efd'
down_revision = '07490ad2fd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('plant_user_id_fkey', 'plant', type_='foreignkey')
    op.drop_column('plant', 'user_id')
    op.add_column('post', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'plant', ['plant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'plant_id')
    op.drop_column('post', 'category')
    op.add_column('plant', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plant_user_id_fkey', 'plant', 'user', ['user_id'], ['id'])
    op.drop_table('bookmark')
    op.drop_table('plant_book')
    # ### end Alembic commands ###
